name: Documentation

on:
  push:
    branches:
      - main

jobs:

  changes:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'taidevops/ingress-nginx')
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            docs:
              - 'docs/**/*'

  docs:
    name: Update
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (github.repository == 'taidevops/ingress-nginx') &&
      (needs.changes.outputs.docs == 'true')

    permissions:
      contents: write # needed to write releases

    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy
        uses: ./.github/actions/mkdocs
        env:
          PERSONAL_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
